version: "3.9"

services:
  db:
    image: mysql:8.4
    container_name: laravel_db
    environment:
      MYSQL_DATABASE: devops_project
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: siddik
      MYSQL_PASSWORD: siddik
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    depends_on:
      - db
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    networks:
      - laravel_net

volumes:
  db_data:

networks:
  laravel_net:
